### ISSUE TITLE
Doesnt work on online matches with signed account.

### ISSUE THREAD

**Issue by 8nine20** [vanflux/chess-bot#1]
only works when you're not signed into an account. but if you're signed into a chess account and you play online(live) it doesnt work. also have you thought about  making it chrome compatible?

**Comment by vanflux** [comment]
I tried to play an online match with signed account now, it worked.
I have few questions, what exactly doesnt work, the bot doesnt load at all, the moves are not highlighted? What is your browser version?
Chrome compatibility is possible, but the injection is a bit more difficult than we have now (example: [gameHook.ts](https://github.com/vanflux/chess-bot/blob/main/src/background/hooks/gameHook.ts)). This is because the manifest v2 deprecation...

**Comment by 8nine20** [comment]
The bot loads and the moves are highlighted. the problem is that I cannot click on the chess.com HOME OR PLAY buttons on the sidebar. the only way I can access the play site is when i type in chess.com/play, and when I try to play the game loads as usual the extension appears and all that. but for some reason the opponent I go against cannot make a move the game just auto-aborts
also im using  Firefox 97 on Windows 10
my opponent can only make a move when im signed out and im playing as a guest idk why tho
![Capture](https://user-images.githubusercontent.com/95322626/154888185-96a8985d-d814-4648-8f5e-0b4d97f5aa6c.PNG)
.
